### ISSUE TITLE
since version 0.3.25 migration is throwing error if database_type is not provided in ConfigFile

### ISSUE THREAD

**Issue by arunzone** [jasondcamp/pyway#80]
Error stacktrace:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/vagrant/src/onlife_chat_to_point_of_interest/skeleton.py", line 56, in <module>
    run()
  File "/vagrant/src/onlife_chat_to_point_of_interest/skeleton.py", line 52, in run
    main(sys.argv[1:])
  File "/vagrant/src/onlife_chat_to_point_of_interest/skeleton.py", line 41, in main
    _migrate()
  File "/vagrant/src/onlife_chat_to_point_of_interest/skeleton.py", line 33, in _migrate
    Migrate(config).run()
    ^^^^^^^^^^^^^^^
  File "/tmp/development/lib/python3.11/site-packages/pyway/migrate.py", line 15, in __init__
    self._db = factory(args.database_type)(args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by jasondcamp** [comment]
Added a check of common settings before following the code path
